### ISSUE TITLE
how to use bloomfilter set expire time

### ISSUE THREAD

**Issue by luoqishuai** [jaybaird/python-bloomfilter#37]
I want to use bloomfilter in scrapy_redis. scrapy_redis has a large number of url need to filter.
If i use the bloomfilter for a few weeks. Linux memory will boom.So i want use bloomfilter to filter 7 days(or other time) url.What shou i do? Can you give me some adices?

**Comment by luoqishuai** [comment]
If you don't understand or have no free time .Please tell me. Thanks.

**Comment by kleinron** [comment]
I think you need some kind of aging Bloom filter, as described [here](http://matthias.vallentin.net/blog/2011/06/a-garden-variety-of-bloom-filters/).
I'm not sure if this repo contains such implementation.

**Comment by luoqishuai** [comment]
Thank you for your help.
